### ISSUE TITLE
[Feature Request] Deep extend.

### ISSUE THREAD

**Issue by AaronVasquez** [Raynos/xtend#32] opened 2016-06-29 20:38 UTC
It would be nice to support recursive xtend.

**Comment by roobie** [comment] 2017-02-01 19:55
I vote against this, because there is value in keeping this library as simple as possible. If one need that functionality, there are alternatives such as [deep-extend](https://www.npmjs.com/package/deep-extend)

**Comment by michaelfranzl** [comment] 2017-04-25 16:07
It seems the functionality is the same as [Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

**Comment by styfle** [comment] 2017-06-09 19:54
@michaelfranzl Yep. I just confirmed by replacing both files and running tests.

### immutable.js
```js
const extend = (a, b) => Object.assign({}, a, b);
module.exports = extend;
```

### mutable.js
```js
const extend = (a, b) => Object.assign(a, b);
module.exports = extend;
```

### Test Results

```sh
> node test

TAP version 13
# merge
ok 1 should be equivalent
# replace
ok 2 should be equivalent
# undefined
ok 3 should be equivalent
ok 4 should be equivalent
# handle 0
ok 5 should be equivalent
ok 6 should be equivalent
# is immutable
ok 7 should be equal
# null as argument
ok 8 should be equivalent
# mutable
ok 9 should be equal
# null prototype
ok 10 should be equivalent
# null prototype mutable
ok 11 should be equal

1..11
# tests 11
# pass  11

# ok
```

**Comment by janandjill** [comment] 2018-02-03 06:01
Can we do deep-extend. He seems to be staying one step ahead and this is my 4th phone being destroyed

**Comment by Raynos** [comment] 2020-08-10 09:23
Out of scope.

**Closed by Raynos** 2020-08-10 09:23 UTC
